### ISSUE TITLE
player limit does not work anymore

### ISSUE THREAD

**Issue by verymilan** [SmallJoker/names_per_ip#7]
Hi there, while the mod does not throw errors, the playerlimit no longer works.
I sadly cannot tell if there is anything that may have triggered it, for now i had the theory that it may has something todo with the minetest version?

The server is ... older than i thought - at march 6 2019, c735497a65c8133c0df6b7ee7fc87dc4725994e6
May it be too old instead of too new, which i originally guessed?

**Comment by SmallJoker** [comment]
https://github.com/SmallJoker/names_per_ip/blob/d17ecc54365c5786da9347db23f8678949284949/init.lua#L86-L87

Does this warning show up in your server's `debug.txt` file?
Please count the duplicate IP entries in `ipnames.data`. If there are less similar IPs than the configured maximum, the save/load mechanism is broken - otherwise something goes wrong while adding new accounts to the list.

Will look into this issue. Please consider updating Minetest (current stable: 5.2.0) in the meantime.

**Comment by verymilan** [comment]
Huh, i am sorry, i am not sure why i didn't reply anymore. 
Actually this is still a problem. I have just checked recent logs and there is no such warning.
I also gave that datafile a look and noticed that almost none of the registered players are in there (only 13)....but joining with two of my accounts made these pop up again. Is this intended? I did not see the code for this files rotation... .

Unfortunately the malicious player has not been there for a while...

**Comment by SmallJoker** [comment]
Only newly registered accounts should be added there, though I don't know any more why I wrote the mod like that.
https://github.com/SmallJoker/names_per_ip/blob/d17ecc54365c5786da9347db23f8678949284949/init.lua#L57-L61

When you remove the `ipnames.is_registered(name)` check, does the mod do what you'd expect?

**Comment by SmallJoker** [comment]
7f99133
